BestBank/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.views import static
from basicbank import views
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('admin/', admin.site.urls),
    path('basicbank/',include('basicbank.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('transactions/', include('transactions.urls', namespace='transactions'))
]

accounts/urls.py
from django.urls import path

from .views import UserRegistrationView, LogoutView, UserLoginView

app_name = 'accounts'

urlpatterns = [
    path("login/", UserLoginView.as_view(), name="user_login"),
    path("logout/", LogoutView.as_view(), name="user_logout"),
    path("register/", UserRegistrationView.as_view(), name="user_registration"),
]

basicbank/urls.py
from django.urls import path
from . import views

app_name = 'basicbank'

urlpatterns = [
    path('transfer_money/',views.cust, name= 'transfermoney'),
    path('transfer_details/',views.transfer, name= 'transferdetails'),
    path('customers/',views.cdetails, name= 'customers'),
]

transactions/urls.py
from django.urls import path

from .views import DepositMoneyView, WithdrawMoneyView, TransactionRepostView

app_name = 'transactions'


urlpatterns = [
    path("deposit/", DepositMoneyView.as_view(), name="deposit_money"),
    path("report/", TransactionRepostView.as_view(), name="transaction_report"),
    path("withdraw/", WithdrawMoneyView.as_view(), name="withdraw_money"),
]

accounts/models.py
from decimal import Decimal

from django.contrib.auth.models import AbstractUser
from django.core.validators import (
    MinValueValidator,
    MaxValueValidator,
)
from django.db import models

from .constants import GENDER_CHOICE
from .managers import UserManager


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, null=False, blank=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email

    @property
    def balance(self):
        if hasattr(self, 'account'):
            return self.account.balance
        return 0


class BankAccountType(models.Model):
    name = models.CharField(max_length=128)
    maximum_withdrawal_amount = models.DecimalField(
        decimal_places=2,
        max_digits=12
    )
    annual_interest_rate = models.DecimalField(
        validators=[MinValueValidator(0), MaxValueValidator(100)],
        decimal_places=2,
        max_digits=5,
        help_text='Interest rate from 0 - 100'
    )
    interest_calculation_per_year = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(12)],
        help_text='The number of times interest will be calculated per year'
    )

    def __str__(self):
        return self.name

    def calculate_interest(self, principal):
        """
        Calculate interest for each account type.

        This uses a basic interest calculation formula
        """
        p = principal
        r = self.annual_interest_rate
        n = Decimal(self.interest_calculation_per_year)

        # Basic Future Value formula to calculate interest
        interest = (p * (1 + ((r/100) / n))) - p

        return round(interest, 2)


class UserBankAccount(models.Model):
    user = models.OneToOneField(
        User,
        related_name='account',
        on_delete=models.CASCADE,
    )
    account_type = models.ForeignKey(
        BankAccountType,
        related_name='accounts',
        on_delete=models.CASCADE
    )
    account_no = models.PositiveIntegerField(unique=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(null=True, blank=True)
    balance = models.DecimalField(
        default=0,
        max_digits=12,
        decimal_places=2
    )
    interest_start_date = models.DateField(
        null=True, blank=True,
        help_text=(
            'The month number that interest calculation will start from'
        )
    )
    initial_deposit_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return str(self.account_no)

    def get_interest_calculation_months(self):
        """
        List of month numbers for which the interest will be calculated

        returns [2, 4, 6, 8, 10, 12] for every 2 months interval
        """
        interval = int(
            12 / self.account_type.interest_calculation_per_year
        )
        start = self.interest_start_date.month
        return [i for i in range(start, 13, interval)]


class UserAddress(models.Model):
    user = models.OneToOneField(
        User,
        related_name='address',
        on_delete=models.CASCADE,
    )
    state = models.CharField(max_length=512)
    city = models.CharField(max_length=256)
    pincode = models.PositiveIntegerField()
    country = models.CharField(max_length=256)

    def __str__(self):
        return self.user.email

accounts/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction

from .models import User, BankAccountType, UserBankAccount, UserAddress
from .constants import GENDER_CHOICE


class UserAddressForm(forms.ModelForm):

    class Meta:
        model = UserAddress
        fields = [
            'state',
            'city',
            'pincode',
            'country'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 rounded '
                    'py-3 px-4 leading-tight focus:outline-none '
                    'focus:bg-white focus:border-gray-500'
                )
            })


class UserRegistrationForm(UserCreationForm):
    account_type = forms.ModelChoiceField(
        queryset=BankAccountType.objects.all()
    )
    gender = forms.ChoiceField(choices=GENDER_CHOICE)
    birth_date = forms.DateField()

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'class': (
                    'appearance-none block w-full bg-gray-200 '
                    'text-gray-700 border border-gray-200 '
                    'rounded py-3 px-4 leading-tight '
                    'focus:outline-none focus:bg-white '
                    'focus:border-gray-500'
                )
            })

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
            account_type = self.cleaned_data.get('account_type')
            gender = self.cleaned_data.get('gender')
            birth_date = self.cleaned_data.get('birth_date')

            UserBankAccount.objects.create(
                user=user,
                gender=gender,
                birth_date=birth_date,
                account_type=account_type,
                account_no=(
                    user.id +
                    settings.ACCOUNT_NUMBER_START_FROM
                )
            )
        return user

accounts/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView, RedirectView

from .forms import UserRegistrationForm, UserAddressForm


class HomeView(TemplateView):
    template_name = 'accounts/index.html'

User = get_user_model()

class UserRegistrationView(TemplateView):
    model = User
    form_class = UserRegistrationForm
    template_name = 'accounts/user_registration.html'

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            return HttpResponseRedirect(
                reverse_lazy('transactions:transaction_report')
            )
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        registration_form = UserRegistrationForm(self.request.POST)
        address_form = UserAddressForm(self.request.POST)

        if registration_form.is_valid() and address_form.is_valid():
            user = registration_form.save()
            address = address_form.save(commit=False)
            address.user = user
            address.save()

            login(self.request, user)
            messages.success(
                self.request,
                (
                    f'Thank You For Creating A Bank Account. '
                    f'Your Account Number is {user.account.account_no}. '
                )
            )
            return HttpResponseRedirect(
                reverse_lazy('transactions:deposit_money')
            )

        return self.render_to_response(
            self.get_context_data(
                registration_form=registration_form,
                address_form=address_form
            )
        )

    def get_context_data(self, **kwargs):
        if 'registration_form' not in kwargs:
            kwargs['registration_form'] = UserRegistrationForm()
        if 'address_form' not in kwargs:
            kwargs['address_form'] = UserAddressForm()

        return super().get_context_data(**kwargs)


class UserLoginView(LoginView):
    template_name='accounts/user_login.html'
    redirect_authenticated_user = True


class LogoutView(RedirectView):
    pattern_name = 'home'

    def get_redirect_url(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            logout(self.request)
        return super().get_redirect_url(*args, **kwargs)

templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
   <!-- Required meta tags -->
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <!-- Bootstrap CSS -->
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

   <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet'>

   <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">

   {% block head_extra %}{% endblock %}
   
<title>Basic Banking System</title>
</head>

{% csrf_token %}

<div class="container-fluid">
      

{% block body %}

    {% include 'accounts/navbar.html' %}
        {% include 'accounts/messages.html' %}
                {% block content %}
                <!-- Add content here -->
                {% endblock %}
    {% include 'accounts/footer.html' %}

{% endblock %}

{% block footer_extra %}{% endblock %}

</div>


<link href="https://use.fontawesome.com/releases/v5.0.4/css/all.css" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<style>

    html{
        padding: 0;
        margin: 0;
    }
    
    /* Body */
    
    body {
        font-family:  'Poppins','Roboto', sans-serif !important;
    }
    
      /* Hero  */
      .hero-content{
        height: 100vh;
        background-color: #4341ad ;
        color: #ffffff;
        padding: 3rem;
        border-bottom-left-radius: 45rem;
        border-bottom-right-radius: 45rem;
        margin-bottom: 1vh;
    }
    
    .hero-img{
        height: 70vh;
        width: 100%;
    }
    
    .get-started{
        border-radius: 0.5rem;
        padding: 1rem 2rem;
        font-size: 100%;
        background-color: #fff;
        color: #4341ad!important;
        transition: 0.5s;
    }
    
    .get-started:hover{
        text-decoration: none;
        background-color:#039be5;
        
    }
    
    /* Cards */
    
    .card {
        border-style: none;
    }
    
    #Cd1 {
        width: 100%;
        height: 70%;
        overflow: hidden;
    }
    
    #Cd1 img {
        width: 110vh;
        align-self: center;
        margin:auto;
    }
        
    #Cd2{
        width:95%;
        position: relative;
        left:10%;
    }
    
    #Cd3{
        width:90%;
        position: relative;
    }
    
    #Cd4{
        width:92%;
        position: relative;
    }
    
    #Cd5{
        width:105%;
        position: relative;
    }
    
    #Cd6{
        width:105%;
        position: relative;
    }
    
    #Cd7{
        width:100%;
        position: relative;
    }
    
    
    .contact-content{
        height: 100vh;
        background-color: #4341ad ;
        color: #ffffff;
        padding: 1rem;
        border-top-left-radius: 45rem;
        border-top-right-radius: 45rem;
        margin-top: 1vh;
    }
    input:focus, textarea:focus, keygen:focus, select:focus {
        outline: none;
    }
    
    /* Contact Form Styling */
    .textcenter {
        text-align: center;
    }
    
    .section2 {
        width: 100%;
        margin: 25px;
        padding-left: 0%;
        
    }
    .section2 .contact-img{
        margin:auto;
    }
    .section2 .col2.first {
        float: left;
    }
    .section2 .col2.last {
        float: right;
    }
    .section2 .col2.column2 {
        padding: 25px 150px 0px 0px;
    }
    .section2 span.collig {
        color: #666;
        margin-right: 10px;
        display: inline-block;
    }
    .section2 .sec2addr {
        display: block;
        line-height: 25px;
    }
    .section2 .sec2addr p:first-child {
        margin-bottom: 10px;
    }
    .section2 .sec2contactform input[type="text"], 
    .section2 .sec2contactform input[type="email"],
    .section2 .sec2contactform textarea {
        padding: 15px;
        border: 0;
        border-radius: 5px;
        color: #666;
        background: #EDEDED;
        margin: 7px 0;
    }
    .section2 .sec2contactform textarea {
        width: 100%;
        display: block;
        color: #666;
      border-radius: 5px;
      resize:none;
      margin-bottom: 5%;
    }
    .section2 .sec2contactform input[type="submit"] {
        color:#ffffff;
        background: #10a8f5;
        font-size: 16px;
        cursor: pointer;
    }
    
    .footer {
        margin-top: 0px;  
        padding-top: 20px;
      }
    
    
    /* LINKS */
    
    a:link, a:visited {
        color: var(--link-fg);
        text-decoration: none;
        transition: color 0.5s, background 0.5s;
    }
    
    a:focus, a:hover {
        color: var(--link-hover-color);
        text-decoration: none;
        transition: color 0.5s, background 0.5s;
    }
    
    
    /* TABLES */
    
    table{
        margin: auto;
        width: 70%;
        border-collapse: collapse;
        border-color: var(--border-color);
    
    }
    
    td, th{
        border-bottom: 1px solid var(--hairline-color);
        vertical-align: top;
        padding-top: 5px;
        padding-bottom: 5px;
    }
    
    thead th,
    tfoot td {
        color: var(--body-quiet-color);
        background: var(--body-bg);
        border-top: 1px solid var(--hairline-color);
        border-bottom: 1px solid var(--hairline-color);
    }
    
    
    /* FORM DEFAULTS */
    
    .blk{
        display: block;
        width: 100%;
        padding: 5px 5px;
        font-weight: bold;
    }
    
    input, textarea, select,bform .button {
        margin: auto;
    
    }
    
    input[type=text], input[type=password], input[type=email], input[type=url],
    input[type=number], input[type=tel], textarea, select, .vTextField {
        border: 1px solid black;
        border-radius: 1px;
        padding: 5px 5px;
        color: var(--body-fg);
        background-color: var(--body-bg);
    }
    
    .button, input[type=submit], input[type=button], .submit-row input, a.button {
        background: var(--button-bg);
        padding: 10px 10px;
        border: none;
        border-radius: 4px;
        color: var(--button-fg);
        cursor: pointer;
        transition: background 0.5s;
    }
    
    </style>
    
</body>
</html>

templates/accounts/footer.html
<!-- Footer-->

<footer class="footer" style="background-color: #f1f1f1;">
    <div class="container">
      <div class="row">
        <div class="col-lg-8">
          <p class="m-4">A Project by <b>SHIVAM CHAUDHARY</b> &copy; 2021</p>
        </div>
        <div class="col-lg-4 fixed-right">
           <!-- Facebook -->
    <a
    class="btn btn-link btn-floating btn-lg text-dark m-1"
    href="#!"
    ><i class="fab fa-facebook-f"></i
  ></a>

  <!-- Instagram -->
  <a
    class="btn btn-link btn-floating btn-lg text-dark m-1"
    href="#!"
    ><i class="fab fa-instagram"></i
  ></a>

  <!-- Linkedin -->
  <a
    class="btn btn-link btn-floating btn-lg text-dark m-1"
    href="#!"
    ><i class="fab fa-linkedin"></i
  ></a>
  <!-- Github -->
  <a
    class="btn btn-link btn-floating btn-lg text-dark m-1"
    href="#!"
    ><i class="fab fa-github"></i
  ></a>
  <!-- Google -->
  <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="#!"
      ><i class="fab fa-google"></i
      ></a>

        </div>
      </div>
    </div>
</footer>

templates/accounts/index.html
{% extends 'accounts/base.html' %}

{% block content %}

<!-- hero content starts here -->
    <div class="hero-content container-fluid ">
        <div class="row align-items-center">
          <div class="col-md-6 col-sm-12 text-center" data-aos="fade-up">
            <p>Welcome to</p>
            <br>
            <h1 style="color: #10a8f5; font-size: xx-large; font-weight:bolder;">The Best Bank</h1>
            <br>
            <p>Get the access of your account now in the comfort of your home</p>
            <p>Easy way to transfer money from any where</p>
            <br>
            {% if request.user.is_authenticated %}
            <br>
            <a class="get-started" href="#Cd2">Get Started</a>
            {% else %}
            <a class="get-started" href="{% url 'accounts:user_registration' %}">Register</a>
            {% endif %}
          </div>
          <div class="col-md-6 col-sm-12 text-center" data-aos="fade-left">
            <div class="hero-img-div">
              <img class="hero-img" src="https://raw.githubusercontent.com/Tejesh469/basic-banking-system/ccefdd73357fbe16e23a4167f8cd28f3749bd088/assets/media/hero-img.svg" alt="img-showing-money-transfer" width="500" height="600">
            </div>
          </div>
        </div>
      </div>
      <!-- hero content ends here -->

{% if request.user.is_authenticated %}    
<!-- top card  -->

<div class="row row-cols-1 row-cols-md-3 text-center">
  <br>
  <br>
  <div id="Cd1"><img class="card-img img-fluid text-center" src="https://media.istockphoto.com/vectors/people-clients-consumer-characters-waiting-in-line-in-bank-office-vector-id1148658955?k=6&m=1148658955&s=170667a&w=0&h=3l1K63wC3M137dYH4aSXIwMtpSWUpNjQvkzlXgLulHE=" alt="Card image" >
    <h1 class="card-text text-center " style=" color:#4341ad; font-size: xx-large; font-weight:bolder; margin-top: -3%; margin-bottom: 2%;" >Bank Services</h1>
  </div>  
</div>


<!-- card C2 -->
<div class="row row-cols-1 row-cols-md-3">
  <div class="col">
      <div class="card text-center">
          <img id="Cd2" src="https://image.freepik.com/free-vector/saving-money-financial-concept_74855-7849.jpg" alt="">
          <div class="card-body">
              <h3 class="card-title" style="font-size:x-large; font-weight: bolder;">Deposit Money</h3>
              <p class="card-text">Transfers money into your savings account.</p>
              <br>
              <a href="{% url 'transactions:deposit_money' %}" class="btn btn-warning">Deposit Money</a>
          </div>
      </div>
  </div>

  <!-- card C3 -->

  <div class="col">
      <div class="card text-center">
          <img id="Cd3" src="https://image.freepik.com/free-vector/happy-rich-banker-celebrating-income-growth_74855-5867.jpg" alt="...">
          <div class="card-body">
              <h3 class="card-title" style="font-size:x-large; font-weight: bolder;">Withdraw Money</h3>
              <p class="card-text"> Taking out money from your account at a bank</p>
              <br>
              <a href="{% url 'transactions:withdraw_money' %}" class="btn btn-success">Withdaw Money</a>
          </div>
      </div>
  </div>
  
  <!-- card C4 -->

  <div class="col">
    <div class="card text-center">
        <img id="Cd4" src="https://image.freepik.com/free-vector/mobile-bank-users-transferring-money-currency-conversion-tiny-people-online-payment-cartoon-illustration_74855-14454.jpg" alt="...">
        <div class="card-body">
          <h3 class="card-title" style="font-size:x-large; font-weight: bolder;">Transfer Money</h3>
            <p class="card-text">Transfer Money to anyone from anywhere.</p>
            <br>
            <a href="{% url 'basicbank:transfermoney' %}" class="btn btn-danger">Transfer Money</a>
        </div>
    </div>
</div>
</div>

<!-- card C5 -->

<div class="row row-cols-1 row-cols-md-3">
<div class="col">
    <div class="card text-center">
        <img id="Cd5" src="https://ezipay.africa/wp-content/uploads/2021/05/transfert-argent-ligne-services-bancaires-mobiles_7087-1055.jpg" alt="">
        <div class="card-body">
            <h3 class="card-title" style="font-size:x-large; font-weight: bolder;">Create Account</h3>
            <p class="card-text">Open a new saving account in the Bank.</p>
            <br>
            <a href="{% url 'admin:index' %}" class="btn btn-info">Create Account</a>
        </div>
    </div>
</div>

<!-- card C6 -->

<div class="col">
    <div class="card text-center">
        <img id="Cd6" src="https://img.freepik.com/free-vector/online-transfer-money-with-mobile-banking_7087-1054.jpg?size=626&ext=jpg" alt="...">
        <div class="card-body">
            <h3 class="card-title"style="font-size:x-large; font-weight: bolder;">Transaction History</h3>
            <p class="card-text"> View Transaction Details and History. </p>
            <br>
            <a href="{% url 'basicbank:transferdetails' %}" class="btn btn-warning">Transaction History</a>
        </div>
    </div>
</div>

<!-- card C7 -->

  <div class="col">
        <div class="card text-center">
            <img id="Cd7" src="https://www.rpaywallet.com/blog/wp-content/uploads/2020/07/mobile-wallet.jpg" alt="...">
            <div class="card-body">
                <h3 class="card-title" style="font-size:x-large; font-weight: bolder;">Balance Amount</h3>
                <p class="card-text">View Bank Statement and Mini Statement </p>
                <br>
                <a href="{% url 'transactions:transaction_report' %}" class="btn btn-primary">Balance Amount</a>
            </div>
        </div>
    </div>
</div>
    
<br>
<br>
<br>
<br>
<br>

<!-- Contact form -->

<section class="contact-content">
<div class="container-fluid ">
  <section class="section1 ">
    <div class="textcenter">
      <br>
      <h1 style="color: #10a8f5; font-size: xx-large; font-weight:bolder; margin-top:3%;">Contact Us</h1>
    </div>
  </section>
  <section class=" row align-items-center section2">
    <div class="col-md-6 col-sm-12 text-center" data-aos="fade-left">
      <div class="contact-img-div">
        <img class="contact-img" src="https://atlas.org.il/wp-content/uploads/2019/02/business-dev2.png" alt="" height="80%" width="80%">
      </div>
    </div>
    <div class="col-md-6 col-sm-12 col2 column2 last" data-aos="fade-right">
        <div class=" sec2contactform">
          <h2 style="color: #10a8f5; font-size: x-large; font-weight:bold;">Drop Us a Mail</h2>
          <br>
          <form action="">
            <div>
              <input class="col2 first" type="text" placeholder="FirstName">
              <input class="col2 last" type="text" placeholder="LastName">
            </div>
            <div>
              <input  class="col2 first" type="Email" placeholder="Email">
              <input class="col2 last" type="text" placeholder="Contact Number">
            </div>
            <div >
              <textarea name="textarea" id="" cols="30" rows="7">Your message here...</textarea>
            </div>
            <div><input type="submit" value="Send" id="#sub"></div>
          </form>
        </div>
    </div>
</section>
</div>
</section>

{% endif %}
   
{% endblock %}

templates/accounts/messages.html
{% for message in messages %}
<div class="bg-teal-100 border-t-4 border-teal-500 rounded-b text-teal-900 px-4 py-3 shadow-md mt-2" role="alert">
    <div class="flex">
        <div class="py-1"><svg class="fill-current h-6 w-6 text-teal-500 mr-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M2.93 17.07A10 10 0 1 1 17.07 2.93 10 10 0 0 1 2.93 17.07zm12.73-1.41A8 8 0 1 0 4.34 4.34a8 8 0 0 0 11.32 11.32zM9 11V9h2v6H9v-4zm0-6h2v2H9V5z"/></svg></div>
        <div>
            <p class="font-bold">Success!</p>
            <p class="text-sm">{{ message }}</p>
        </div>
    </div>
</div>
{% endfor %}

templates/accounts/navbar.html
<!-- navbar -->

<nav class="navbar navbar-expand-lg bg-light ">
    <div class="container"><a class="navbar-brand" href="{% url 'home' %}" style="font-weight:bolder; color:#4341ad ;">BEST BANK</a>
        <ul class="nav justify-content-center m-2">
          {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:deposit_money' %}" style="font-weight:bold;">Deposit</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  href="{% url 'transactions:withdraw_money' %}" style="font-weight:bold;">Withdraw</a>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'basicbank:transfermoney' %}" style="font-weight:bold;">Transfer</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'transactions:transaction_report' %}" style="font-weight:bold;">Transaction</a>
            </li>
          <li class="nav-item">
              <a class="nav-link"  href="{% url 'accounts:user_logout' %}" style="font-weight:bold;">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link"  href="{% url 'accounts:user_login' %}" style="font-weight:bold;">Sign In</a>
          </li>
          <li class="nav-item">
              <a class="nav-link"  href="{% url 'accounts:user_registration' %}" style="font-weight:bold;">Sign Up</a>
          </li>
          {% endif %}
        </ul>
    </div>
  </nav>
  

templates/accounts/user_login.html
{% extends 'accounts/base.html' %}

{% block head_title %}Banking System{% endblock %}

{% block content %}
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
            <p class="font-bold">Error!</p>
            <p class="block sm:inline">{{ error }}</p>
        </div>
    {% endfor %}
{% endif %}
<h1 class="font-poppins font-bold text-3xl text-center pb-5 pt-5">Sign In</h1>
<hr>
<div class="w-full mt-10">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
        {% endfor %}
        {% for field in form.visible_fields %}
        <div class="mb-4">
            <label class="block text-black-700 text-md font-bold mb-2" for="{{ field.id_for_label }}">
                {{ field.label }}
            </label>
            <input class="shadow appearance-none border border-gray-500 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" type="{{ field.widget_type }}">
        </div>
            {% if field.errors %}
                {% for error in field.errors %}
                <p class="text-red-600 text-md italic pb-2">{{ error }}</p>
                {% endfor %}
            {% endif %}
        {% endfor %}

        <div class="flex items-center justify-between">
            <button class="bg-blue-500  text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Sign In
            </button>
        </div>
    </form>
</div>
{% endblock %}